---
- name: Generate domain model
  environment:
    RAILS_ENV: "{{ redmine_mode }}"
  become: true
  become_user: "{{ redmine_user }}"
  block:
    - name: Add require gem package setting
      ansible.builtin.lineinfile:
        path: "{{ redmine_home }}/Gemfile.local"
        line: gem 'rails-erd'
      register: append_gemfile_result
    - name: Instal/update gem packages
      ansible.builtin.command:
        cmd: bundle update
        chdir: "{{ redmine_home }}"
      when: append_gemfile_result is changed
    - name: Create/update Rails ERD config
      ansible.builtin.copy:
        content: "{{ document_domain_model_conf | to_nice_yaml }}"
        dest: "{{ redmine_home }}/.erdconfig"
        mode: "0644"
      register: update_domain_mode_config_result
    - name: Generate domain model
      ansible.builtin.command:
        cmd: bundle exec rake erd
        chdir: "{{ redmine_home }}"
      when: >
        update_domain_mode_config_result is changed
        or
        force_update_domain_model_doc | default(false)
- name: Set domain model docment file variable
  ansible.builtin.set_fact:
    document_file_name: "{{ document_domain_model_conf.filename | default('erd') }}"
    document_file_type: "{{ document_domain_model_conf.filetype | default('pdf') }}"
- name: Copy domain model file
  ansible.builtin.copy:
    src: /opt/redmine/{{ document_file_name }}.{{ document_file_type }}
    dest: /vagrant/docs/{{ document_file_name }}.{{ document_file_type }}
    mode: "0644"
    remote_src: true
