---
- name: Webフォント生成用の各種パッケージをインストール
  ansible.builtin.apt:
    name: "{{ document_webfont_packages }}"
  become: true
- name: サブセット
  ansible.builtin.template:
    src: subset_all.txt.j2
    dest: "{{ document_asset_font_dir }}/subset.txt"
    mode: "0644"
  vars:
    ## 日本語WEBフォントをサブセット化する際の参考文字列一覧 | U-618WEB
    ## https://u-618.org/webfont-subset/
    subset_text_files:
      - files/webfont/subset_alphanumeric.txt
      - files/webfont/subset_symbol.txt
      - files/webfont/subset_fullwidth_alphanumeric.txt
      - files/webfont/subset_fullwidth_symbol.txt
      - files/webfont/subset_hiragana.txt
      - files/webfont/subset_katakana.txt
      - files/webfont/subset_kanji.txt
  register: update_subset_font_text_result
- name: サブセットフォント及びWebフォントを生成
  when: >
    update_subset_font_text_result is changed
    or
    force_generate_webfont | default(false)
  block:
    - name: サブセットフォントを生成
      ansible.builtin.command:
        cmd: >
          fonttools subset
          --text-file={{ document_asset_font_dir }}/subset.txt
          --output-file={{ item.output_file | default(item.src | basename) }}
          {{ item.src }}
        chdir: "{{ document_asset_font_dir }}"
      loop: "{{ document_webfont_font_files }}"
      loop_control:
        label: "{{ item.src | basename }}"
    - name: 生成済みのサブセットフォントを抽出
      ansible.builtin.find:
        paths:
          - "{{ document_asset_font_dir }}"
        patterns:
          - "*.ttf"
          - "*.otf"
      register: find_subset_result
    - name: Webフォント(woff形式)を生成
      ansible.builtin.command:
        cmd: sfnt2woff-zopfli {{ item.path }}
        chdir: "{{ document_asset_font_dir }}"
      loop: "{{ find_subset_result.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
    - name: Webフォント(woff2形式)を生成
      ansible.builtin.command:
        cmd: woff2_compress {{ item.path }}
        chdir: "{{ document_asset_font_dir }}"
      loop: "{{ find_subset_result.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
- name: Webフォント定義用のCSSファイルを生成
  ansible.builtin.template:
    src: fonts.css.j2
    dest: "{{ document_asset_css_dir }}/fonts.css"
    mode: "0644"
