---
- name: APIドキュメントの生成
  environment:
    RAILS_ENV: "{{ redmine_mode }}"
  become: true
  become_user: "{{ redmine_user }}"
  block:
    - name: ドキュメントの生成に必要となるgemパッケージの情報を追記
      ansible.builtin.lineinfile:
        path: "{{ redmine_root }}/Gemfile.local"
        line: gem "yard"
      register: append_gemfile_result
    - name: gemパッケージのインストール/更新
      ansible.builtin.command:
        cmd: bundle update
        chdir: "{{ redmine_root }}"
      when: append_gemfile_result is changed
    - name: APIドキュメントが生成済みかどうかをチェック
      ansible.builtin.stat:
        path: "{{ redmine_root }}/doc/app"
      register: redmine_api_doc_dir_stat_result
    - name: YARDドキュメントを生成
      ansible.builtin.command:
        cmd: bundle exec rake yard
        chdir: "{{ redmine_root }}"
      when: >
        not redmine_api_doc_dir_stat_result.stat.exists
        or
        force_update_api_doc | default(false)
      register: generate_api_doc_result
- name: APIドキュメント格納用ディレクトリを生成
  ansible.builtin.file:
    path: "{{ document_api_dir }}"
    state: directory
    mode: "0755"
- name: 生成済みのAPIドキュメントをドキュメント格納ディレクトリにコピー
  ansible.posix.synchronize:
    src: "{{ redmine_root }}/doc/app/"
    dest: "{{ document_api_dir }}/"
    delete: true
  delegate_to: "{{ inventory_hostname }}"
