---
# code: language=ansible
- name: Generate operational and maintenance report
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update package cache and packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
  roles:
    - role: report
      tags: role_report
    - role: dns
      tags: role_dns
  tasks: []
