---
roles:
  - name: common
    src: https://github.com/wate/ansible-role-common
    version: develop
  - name: nodejs
    src: https://github.com/wate/ansible-role-nodejs
    version: develop
  - name: logrotate
    src: https://github.com/wate/ansible-role-logrotate
    version: develop
  - name: opendkim
    src: https://github.com/wate/ansible-role-opendkim
    version: develop
  - name: dehydrated
    src: https://github.com/wate/ansible-role-dehydrated
    version: develop
  - name: nginx
    src: https://github.com/wate/ansible-role-nginx
    version: develop
  - name: redis
    src: https://github.com/wate/ansible-role-redis
    version: develop
  - name: mariadb
    src: https://github.com/wate/ansible-role-mariadb
    version: develop
  - name: redmine
    src: https://github.com/wate/ansible-role-redmine
    version: develop
  - name: tools
    src: https://github.com/wate/ansible-role-tools
    version: develop
  - name: backup
    src: https://github.com/wate/ansible-role-backup
    version: develop
  - name: mackerel_agent
    src: https://github.com/wate/ansible-role-mackerel_agent
    version: develop
  - name: dns
    src: https://github.com/wate/ansible-role-dns
    version: develop
  - name: hedgedoc
    src: https://github.com/wate/ansible-role-hedgedoc
    version: develop
  ### 以下、ローカル検証環境用
  - name: mailpit
    src: https://github.com/wate/ansible-role-mailpit
    version: develop
  - name: spamassassin
    src: https://github.com/wate/ansible-role-spamassassin
    version: develop
  - name: font
    src: https://github.com/wate/ansible-role-font
    version: develop
collections: []
