---
roles:
  - name: common
    src: https://github.com/wate/ansible-role-common
    version: develop
  - name: nodejs
    src: https://github.com/wate/ansible-role-nodejs
    version: develop
  - name: nginx
    src: https://github.com/wate/ansible-role-nginx
    version: develop
  - name: mariadb
    src: https://github.com/wate/ansible-role-mariadb
    version: develop
  - name: dehydrated
    src: https://github.com/wate/ansible-role-dehydrated
    version: develop
  - name: redmine
    src: https://github.com/wate/ansible-role-redmine
    version: develop
  - name: mailpit
    src: https://github.com/wate/ansible-role-mailpit
    version: develop
  - name: spamassassin
    src: https://github.com/wate/ansible-role-spamassassin
    version: develop
  - name: tools
    src: https://github.com/wate/ansible-role-tools
    version: develop
collections: []
