---
# code: language=ansible
- name: Verify
  hosts: all
  become: true
  module_defaults:
    ansible.builtin.shell:
      executable: /bin/bash
  gather_facts: true
  tags: verify
  vars:
    expect_hostname: "{{ lookup('env', 'VAGRANT_VM_DOMAIN') | default('redmine.local', true) }}"
    expect_dkim_sign_domains:
      - "{{ lookup('env', 'VAGRANT_VM_DOMAIN') | default('redmine.local', true) }}"
    # expect_dehydrated_ssl_domains:
    #   - redmine.dev
    #   - redmine.page > redmine.page
    #   - redmine.community *.redmine.community > redmine.community
    verify_https_port: false
    verify_lookup_dns: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Find test files
      ansible.builtin.set_fact:
        test_files: "{{ lookup('fileglob', 'verify/*.yml', wantlist=True) | sort }}"
    - name: Include test file
      ansible.builtin.include_tasks:
        file: "{{ test_file }}"
      loop: "{{ test_files }}"
      loop_control:
        loop_var: test_file
        label: "{{ test_file | basename }}"
