# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  notify:
    internal: true
    silent: true
    cmds:
      - afplay /System/Library/Sounds/Glass.aiff
  create:
    desc: Run Vagrant up
    cmds:
      - vagrant up
      - task: notify
  build:
    desc: Run Vagrant provision
    cmds:
      - vagrant provision
      - task: notify
  verify:
    desc: Run Vagrant provision
    cmds:
      - vagrant provision
      - task: notify
  report:
    desc: Run Vagrant provision
    cmds:
      - vagrant provision
      - task: notify
