---
# code: language=ansible
- name: Assert Nginx package
  ansible.builtin.assert:
    that:
      - ansible_facts.packages['nginx']
- name: Assert Nginx service
  ansible.builtin.assert:
    that:
      - ansible_facts.services['nginx.service']
      - ansible_facts.services['nginx.service']['state'] == 'running'
      - ansible_facts.services['nginx.service']['status'] == 'enabled'
- name: Assert Web server port(HTTP)
  ansible.builtin.assert:
    that:
      - 80 in listen_tcp_posts
- name: Assert Web server port(HTTPS)
  ansible.builtin.assert:
    that:
      - 443 in listen_tcp_posts
  when: verify_https_port | default(true)
