---
# code: language=ansible
- name: Assert dehydrated package
  ansible.builtin.assert:
    that:
      - ansible_facts.packages['dehydrated']
    success_msg: "dehydrated package is installed"
    fail_msg: "dehydrated package is not installed"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Check additional setting file
  ansible.builtin.stat:
    path: /etc/dehydrated/conf.d/local.sh
  register: additional_setting_file_result
- name: Assert additional setting file
  ansible.builtin.assert:
    that:
      - additional_setting_file_result.stat.exists
    success_msg: "dehydrated additional setting file exists"
    fail_msg: "dehydrated additional setting file does not exist"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Check hook setting file
  ansible.builtin.stat:
    path: /etc/dehydrated/hook.sh
  register: hook_setting_file_result
- name: Assert domain setting file
  ansible.builtin.assert:
    that:
      - hook_setting_file_result.stat.exists
      - hook_setting_file_result.stat.mode == '0750'
    success_msg: "dehydrated hook setting file is properly configured"
    fail_msg: "dehydrated hook setting file is not properly configured"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Check domain setting file
  ansible.builtin.stat:
    path: /etc/dehydrated/domains.txt
  register: domain_setting_file_result
- name: Assert domain setting file
  ansible.builtin.assert:
    that:
      - domain_setting_file_result.stat.exists
    success_msg: "dehydrated domain setting file exists"
    fail_msg: "dehydrated domain setting file does not exist"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Test SSL domain setting
  block:
    - name: Check SSL domain setting
      ansible.builtin.command:
        cmd: cat /etc/dehydrated/domains.txt
      changed_when: false
      register: dehydrated_domains_txt_result
    - name: Assert SSL domain setting
      ansible.builtin.assert:
        that: "ssl_domain_txt in dehydrated_domains_txt_result.stdout_lines"
        success_msg: "SSL domain setting is configured"
        fail_msg: "SSL domain setting is not configured"
        quiet: "{{ assert_quiet_mode | default(true) }}"
      loop: "{{ expect_dehydrated_ssl_domains | default([]) }}"
      loop_control:
        loop_var: ssl_domain_txt
        label: "{{ ssl_domain_txt }}"
