---
# code: language=ansible
- name: Assert packages
  ansible.builtin.assert:
    that:
      - ansible_facts.packages['rclone']
      - ansible_facts.packages['restic']
- name: Test cron job
  become: true
  become_user: redmine
  block:
    - name: Check Redmine data backup cron job
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          crontab -l | grep "Ansible: role:backup/setting:"
        executable: /usr/bin/bash
      failed_when: crontab_result.rc > 1
      changed_when: false
      register: crontab_result
    - name: Assert Redmine data backup cron job
      ansible.builtin.assert:
        that:
          - crontab_result.rc == 0
