---
# code: language=ansible
- name: Assert mackerel-agent package
  ansible.builtin.assert:
    that:
      - ansible_facts.packages['mackerel-agent'] is defined
      - ansible_facts.packages['mackerel-agent-plugins'] is defined
      - ansible_facts.packages['mackerel-check-plugins'] is defined
    success_msg: "Mackerel packages are installed"
    fail_msg: "Mackerel packages are not installed"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Check environment variable
  ansible.builtin.command:
    cmd: grep MYSQL_PASSWORD= /etc/default/mackerel-agent
  failed_when: env_var_result.rc > 1
  changed_when: false
  register: env_var_result
- name: Assert environment variable
  ansible.builtin.assert:
    that:
      - env_var_result.rc == 0
    success_msg: "Mackerel environment variable is configured"
    fail_msg: "Mackerel environment variable is not configured"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Assert mackerel-agent service
  ansible.builtin.assert:
    that:
      - ansible_facts.services['mackerel-agent.service'] is defined
    success_msg: "Mackerel agent service exists"
    fail_msg: "Mackerel agent service does not exist"
    quiet: "{{ assert_quiet_mode | default(true) }}"
- name: Assert running mackerel-agent service
  ansible.builtin.assert:
    that:
      - ansible_facts.services['mackerel-agent.service']['status'] == 'enabled'
      - ansible_facts.services['mackerel-agent.service']['state'] == 'running'
    success_msg: "Mackerel agent service is running and enabled"
    fail_msg: "Mackerel agent service is not properly running or enabled"
    quiet: "{{ assert_quiet_mode | default(true) }}"
  when: mackerel_agent_api_key | default('') | length > 0
