---
# code: language=ansible
- name: Test DNS
  when: verify_lookup_dns | default(false)
  block:
    - name: Assert A recode
      ansible.builtin.assert:
        that:
          - ansible_facts.default_ipv4.address in {{ query('community.dns.lookup', redmine_hostname + '.', type='A') }}
      when: ansible_facts.default_ipv4.address is defined
    - name: Assert AAAA recode
      ansible.builtin.assert:
        that:
          - ansible_facts.default_ipv6.address in {{ query('community.dns.lookup', redmine_hostname + '.', type='AAAA') }}
      when: ansible_facts.default_ipv6.address is defined
